### ISSUE TITLE
涉及PVP的模式，在多个玩家之间同步关卡id～

### ISSUE THREAD

**Issue by aoxu** [aoxu/std2#148]
比如被动PVP模式，A玩家匹配到B玩家打过的一个分数，以这个分数为目标去挑战～
同一个区域的同一个模式也有多个关卡，而且这些关卡之间的分数很可能是不同的～那么B玩家可能打的是关卡1，而A玩家如果打的是关卡2，这里隐含的问题就是，2个玩家打的关卡不同根本就不具备可比性～
基于PVP的公平性，应该在B玩家打出来一个分数的时候，就把他打的关卡（用id唯一指定）同步到服务器的记录里，A玩家在匹配到B玩家的时候，不仅要拉下来他的分数，也要拉下来他的关卡id，确保两个玩家是在同一关里对战～
这样的话，从战前准备UI开始就能看到这个关卡的信息（比如将要面对的小怪），直到战中～
主动PVP模式也有同样的问题～

**Comment by cokeTsang** [comment]
主动PVP不存在此问题，被动PVP相关在被动PVP匹配规则优化时会做。
