### ISSUE TITLE
飞船冲刺场景，场景图移动速度可配置（随阶段）～

### ISSUE THREAD

**Issue by aoxu** [aoxu/std2#153]
原始需求是飞船冲刺的场景，需要在不同阶段，切换成不同的场景图移动速度～（同理，dash奖励场景也有同样需求）
现在的关卡配置层级，自顶向下是这样的：
```
stage
level -- 飞船冲刺场景的顶层是一个level
round
enemy+prop
wave
group
extendBoss
boss
```
疑问是：
现在的场景不同阶段是通过不同wave实现的，场景移动速度可以配置在wave里吗？还是配在round里更合理？
如果是配置在round里，是不是这样：
```lua
-- stageRound.lua
roundspaceship1 = {
        enemy = "enemyspaceship1",
        prop = "propNone",
        backgroundSpeed = 20, -- 不配的话，默认取全局的速度
},
```

**Comment by cqusyc** [comment]
room = {
            [1] = {
                score = "1",duration = 40,
                level = {"area1pvelevel1",},
                roundCount = 1,
                reward = {
                    {type = "dash", item = {char = "dash", waveId = "9020", delay = {15,},}, level = "dash1", speed = {1}},
                },
                sprint = {level = "levelspaceship1", speed = {1}},
                extraWave = "stage1",
                health = "area1",
                score = "1",
            },
        },

**Comment by aoxu** [comment]
完美～
