### ISSUE TITLE
飞船冲刺时，技能变出来的金币支持炸出多个～

### ISSUE THREAD

**Issue by aoxu** [aoxu/std2#157]
原有配置里
```
spaceShipConfig.Add("skill", new Dictionary<string,object>(){{"cooldown", 4}, {"gold", 10}});
```
gold的数值意思改成炸出的金币个数，每个金币与其他飘出来的金币保持一模一样的价值～
炸出来的逻辑是，在固定的半径范围（1.2）以内随机分布配置个数的金币～

**Comment by cqusyc** [comment]
spaceShipConfig.Add("skill", new Dictionary<string,object>(){{"cooldown", 4}, {"gold", 10}, {"count", 10}}); 添加count字段

**Comment by aoxu** [comment]
已验证～
