### ISSUE TITLE
好友Boss，我协助了好友，击杀成功了，我自己没有奖励。  p0

### ISSUE THREAD

**Issue by nearth** [aoxu/std2#201]

**Comment by cqnature** [comment]
{
  "174": {
    "20170727194913": {
      "bossHealth": 0,
      "bossStageHealth": 0,
      "bossStage": 6,
      "closeTime": 1501170553,
      "stageId": 17,
      "areaId": 3,
      "isSacrifice": false,
      "sacrificeReward": false,
      "sacrificeStartRewardId": 0,
      "sacrificeKillRewardId": 0,
      "invited": [
        172,
        188
      ],
      "helped": {
        "172": {
          "userId": 172,
          "startStage": 2,
          "endStage": 3,
          "startBossHealth": 0.849006534,
          "endBossHealth": 0.683400869,
          "time": 1501156853
        },
        "188": {
          "userId": 188,
          "startStage": 4,
          "endStage": 4,
          "startBossHealth": 0.612612545,
          "endBossHealth": 0.476231366,
          "time": 1501163142
        }
      },
      "reward": {
        "rewardId": 2010,
        "bossUserId": 174,
        "status": true,
        "helpUserId": "188",
        "bossId": "20170727194913",
        "sacrificeStartReward": false,
        "sacrificeKillReward": false
      }
    }
  }
}
bossOfFriends接口返回的数据结构不对。reward应该是个数组。 @cokeTsang

**Comment by nearth** [comment]
我看到了奖励，但是按钮是不可以领取状态。

**Comment by cqnature** [comment]
Text received from server:{"time":1501481836,"requestDataMd5":"","answer":"d1f3d478544829e6f3c9b2fd2499d2ad","message":"{\"mod\":\"friendBossMessage\",\"act\":\"update\",\"data\":{\"262\":{\"20170731141248\":{\"bossHealth\":0,\"bossStageHealth\":0,\"bossStage\":6,\"closeTime\":1501481836,\"stageId\":17,\"areaId\":3,\"isSacrifice\":false,\"sacrificeReward\":false,\"sacrificeStartRewardId\":0,\"sacrificeKillRewardId\":0,\"invited\":[261],\"helped\":{\"261\":{\"userId\":261,\"startStage\":1,\"endStage\":2,\"startBossHealth\":1,\"endBossHealth\":0.8610211,\"time\":1501481643}}}}}}"}
击杀后推送的消息中没有奖励信息。 @cokeTsang
