### ISSUE TITLE
交火模式进去就崩溃

### ISSUE THREAD

**Issue by Zimering** [aoxu/std2#254]

**Comment by cqusyc** [comment]
NullReferenceException: Object reference not set to an instance of an object
PVPBattleTransitionWindow.OnInit () (at Assets/Game/Scripts/Game/Education/Controller/Popup/BattlePrepare/PVPBattleTransitionWindow.cs:93)
FairyGUI.Window._init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:433)
FairyGUI.Window.__uiLoadComplete () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:427)
PVPBattleTransitionUISource.Load (FairyGUI.UILoadCallback callback) (at Assets/Game/Scripts/Game/Education/Controller/Popup/BattlePrepare/PVPBattleTransitionWindow.cs:27)
FairyGUI.Window.Init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:367)
FairyGUI.Window.__onShown () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:455)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BroadcastEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:358)
FairyGUI.EventListener.BroadcastCall () (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:222)
FairyGUI.Container.AddChildAt (FairyGUI.DisplayObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/Core/Container.cs:149)
FairyGUI.GComponent.ChildStateChanged (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:729)
FairyGUI.GComponent.AddChildAt (FairyGUI.GObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:213)
FairyGUI.GComponent.AddChild (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:171)
FairyGUI.GRoot.ShowPopup (FairyGUI.GObject popup, FairyGUI.GObject target, System.Object downward) (at Assets/Plugins/FairyGUI/Scripts/UI/GRoot.cs:360)
FairyGUI.GRoot.ShowPopup (FairyGUI.GObject popup) (at Assets/Plugins/FairyGUI/Scripts/UI/GRoot.cs:320)
PVPBattlePrepareWindow.GoBattleEvent () (at Assets/Game/Scripts/Game/Education/Controller/Popup/BattlePrepare/PVPBattlePrepareWindow.cs:206)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1 addChain) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:288)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:330)
FairyGUI.EventListener.BubbleCall (System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:194)
FairyGUI.Stage.HandleMouseEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:827)
FairyGUI.Stage.HandleEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:659)
FairyGUI.Stage.InternalUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:502)
FairyGUI.StageEngine.LateUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/StageEngine.cs:18)
