### ISSUE TITLE
好友Boss，进入后报错

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/std2#258]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[System.Object].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
ListConvert.objectValue[Object] (System.Collections.Generic.List`1 list, Int32 index) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Convert/ListConvert.cs:10)
ListConvert.dictionaryValue[Object,Object] (System.Collections.Generic.List`1 list, Int32 index) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Convert/ListConvert.cs:23)
ListConvert.dictionaryValue[Object] (System.Collections.Generic.List`1 list, Int32 index) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Convert/ListConvert.cs:17)
GamePlay.PigKingDisplay.updateStageParameter (Int32 stage, Boolean reward) (at Assets/Game/Scripts/GamePlay/Skill/Data/Boss/Display/PigKing/PigKingDisplay.cs:121)
GamePlay.PigKingDisplay.startWithUnit (GamePlay.Unit unit) (at Assets/Game/Scripts/GamePlay/Skill/Data/Boss/Display/PigKing/PigKingDisplay.cs:37)
GamePlay.SkillManager.startSkill (GamePlay.Skill skill) (at Assets/Game/Scripts/GamePlay/Skill/SkillManager.cs:101)
GamePlay.SkillManager.addSkill (GamePlay.Skill skill) (at Assets/Game/Scripts/GamePlay/Skill/SkillManager.cs:80)
GamePlay.SkillManager.triggerSkillInterval (System.String t, System.String tag, Boolean needReset, System.Collections.Generic.Dictionary`2 parameters, Int32 order, Boolean needRemove) (at Assets/Game/Scripts/GamePlay/Skill/SkillManager.cs:437)
GamePlay.SkillManager.triggerSkillInterval (System.String t, System.String tag, Boolean needReset, System.Collections.Generic.Dictionary`2 parameters, Int32 order) (at Assets/Game/Scripts/GamePlay/Skill/SkillManager.cs:406)
GamePlay.SkillManager.triggerSkillInterval (System.String t, System.String tag, Boolean needReset, System.Collections.Generic.Dictionary`2 parameters) (at Assets/Game/Scripts/GamePlay/Skill/SkillManager.cs:401)
GamePlay.Unit.triggerSkillInterval (System.String t, System.String tag, Boolean needReset, System.Collections.Generic.Dictionary`2 parameters) (at Assets/Game/Scripts/GamePlay/Unit/Extensions/Categroy/Unit+Skill.cs:32)
GamePlay.BattleUnit.loadDisplay (System.String displayType) (at Assets/Game/Scripts/GamePlay/Unit/Extensions/Categroy/BattleUnit+Skill.cs:23)
GamePlay.HallBoss.loadDisplay () (at Assets/Game/Scripts/GamePlay/Unit/Object/Boss/HallBoss.cs:157)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
GamePlay.Unit.runFunc (GamePlay.UnitFunc obj, System.Object target) (at Assets/Game/Scripts/GamePlay/Unit/Extensions/Categroy/Unit+Func.cs:204)
GamePlay.Unit.runFuncs (System.Collections.Generic.List`1 funcs) (at Assets/Game/Scripts/GamePlay/Unit/Extensions/Categroy/Unit+Func.cs:178)
GamePlay.Unit.runFixNextFuncs () (at Assets/Game/Scripts/GamePlay/Unit/Extensions/Categroy/Unit+Func.cs:169)
GamePlay.Unit.update (Single dt) (at Assets/Game/Scripts/GamePlay/Unit/Object/Unit.cs:539)
GamePlay.BattleUnit.update (Single dt) (at Assets/Game/Scripts/GamePlay/Unit/Object/BattleUnit.cs:130)
GamePlay.Boss.update (Single dt) (at Assets/Game/Scripts/GamePlay/Unit/Object/Boss/Boss.cs:488)
GamePlay.UnitManager.updateUnit (Single dt, .ExtendList`1 units) (at Assets/Game/Scripts/GamePlay/Unit/Data/UnitManager.cs:98)
GamePlay.UnitManager.update (Single dt) (at Assets/Game/Scripts/GamePlay/Unit/Data/UnitManager.cs:49)
GamePlay.BaseNode.update (Single dt) (at Assets/Game/Scripts/GamePlay/Base/Node/BaseNode.cs:109)
GamePlay.BattleNode.update (Single dt) (at Assets/Game/Scripts/GamePlay/Battle/Node/BattleNode.cs:388)
GamePlay.CCNode.iterateUpdate (Single dt) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Node/CCNode+Update.cs:59)
GamePlay.CCNode.iterateUpdate (Single dt) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Node/CCNode+Update.cs:56)
GamePlay.CCNode.iterateUpdate (Single dt) (at Assets/Plugins/Scripts/GamePlay/Common/Extensions/Category/Node/CCNode+Update.cs:56)
GamePlay.BaseScene.Update () (at Assets/Game/Scripts/GamePlay/Base/Node/BaseScene.cs:171)

**Comment by cqusyc** [comment]
战中传入的boss起始阶段为0
