### ISSUE TITLE
白熊、踢腿龙宠物bug（内详）～

### ISSUE THREAD

**Issue by aoxu** [aoxu/std2#266]
白熊（id = 2，skill id = 274）一带进战斗就变成合体状态了（应该是点技能触发合体，然后自动触发吼技能），持续时间到了也没有变回英雄～
踢腿龙（id = 7，skill id = 403）的技能报错，打不出子弹～

**Comment by aoxu** [comment]
2代合体状态通用逻辑（适用于2代所有合体宠物）
开始和结束：点击技能按钮触发合体，技能effectTime（持续时间）结束则从合体回到英雄状态
合体期间无敌，受到攻击不受伤害（不扣燃料），英雄的燃料保持按时间消耗。
如果小怪撞到合体宠物身上撞死，玩家不得分，只有被击杀的小怪才得分。

**Comment by cqusyc** [comment]
合体逻辑已修改
白熊新增技能 404
新增死神 id = 10，skill id = 405

**Comment by aoxu** [comment]
已验证～
