### ISSUE TITLE
维京人好友boss问题记录

### ISSUE THREAD

**Issue by nerodragon** [aoxu/std2#384]
1.boss自身血条（1代红色血条+boss名字）和阶段血条同时存在。
2.boss受击及切阶段没有播掉金币的动画同时实际没有得到金币。
3.boss不会切阶段，必须发完当前招式。
4.维京人的鱼没有刚体

**Comment by cqusyc** [comment]
第三条是废话，一直都是这个逻辑，如果要修改，提出具体方案
