### ISSUE TITLE
宠物升星界面报错。   p1

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/std2#697]
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.Object].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
MonsterDataHandler.DataBaseGetLevelConfig (Int32 monsterId, Int32 grade, Int32 level) (at Assets/Game/Scripts/Game/Data/DataHandler/Singleton/DataHandler/MonsterDataHandler.cs:672)
MonsterInstanceData.get_maxLevel () (at Assets/Game/Scripts/Game/Data/DataHandler/Singleton/DataStruct/Monster/MonsterInstanceData.cs:181)
MonsterInstanceData.get_isMaxLevel () (at Assets/Game/Scripts/Game/Data/DataHandler/Singleton/DataStruct/Monster/MonsterInstanceData.cs:193)
MonsterDataHandler.CheckMonsterCanUpgradeWithOnly (Int32 instanceId) (at Assets/Game/Scripts/Game/Data/DataHandler/Singleton/DataHandler/MonsterDataHandler.cs:171)
MonsterUpgradeWindow.ReloadTabButtonStatus () (at Assets/Game/Scripts/Game/Education/Controller/Popup/HeroMonster/Monster/MonsterUpgradeWindow.cs:81)
MonsterUpgradeWindow.ReloadData () (at Assets/Game/Scripts/Game/Education/Controller/Popup/HeroMonster/Monster/MonsterUpgradeWindow.cs:121)
MonsterUpgradeWindow.OnInit () (at Assets/Game/Scripts/Game/Education/Controller/Popup/HeroMonster/Monster/MonsterUpgradeWindow.cs:61)
FairyGUI.Window._init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:433)
FairyGUI.Window.Init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:376)
FairyGUI.Window.__onShown () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:455)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BroadcastEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:358)
FairyGUI.EventListener.BroadcastCall () (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:222)
FairyGUI.Container.AddChildAt (FairyGUI.DisplayObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/Core/Container.cs:149)
FairyGUI.GComponent.ChildStateChanged (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:725)
FairyGUI.GComponent.AddChildAt (FairyGUI.GObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:207)
FairyGUI.GComponent.AddChild (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:165)
FairyGUI.GRoot.ShowPopup (FairyGUI.GObject popup, FairyGUI.GObject target, System.Object downward) (at Assets/Plugins/FairyGUI/Scripts/UI/GRoot.cs:377)
FairyGUI.GRoot.ShowPopup (FairyGUI.GObject popup) (at Assets/Plugins/FairyGUI/Scripts/UI/GRoot.cs:337)
Desc_EduHeroMonster.HeroMonsterItemNode.InfoEvent () (at Assets/Game/Scripts/Game/Education/Component/Desc_EduHeroMonster/HeroMonsterItemNode.cs:380)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1 addChain) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:288)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:330)
FairyGUI.EventListener.BubbleCall (System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:194)
FairyGUI.Stage.HandleMouseEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:827)
FairyGUI.Stage.HandleEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:659)
FairyGUI.Stage.InternalUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:502)
FairyGUI.StageEngine.LateUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/StageEngine.cs:18)

**Comment by Kinderzhang** [comment]
修改了逻辑 加了判断 模拟器出现 先找我确认

**Comment by JeffreyXsu** [comment]
暂未重现，后续再看下
