### ISSUE TITLE
WebSocket 获取checkToken 异常

### ISSUE THREAD

**Issue by Kinderzhang** [aoxu/std2#747]
WebSocket 获取checkToken 异常 获取一个新的checkToken 当前请求一直停滞。
触发条件：
进入战中， 关闭wifi。 退出游戏，弹出菊花转。重新连wifi。菊花转会一直存在。 日志是请求超时。然后token失效，重新获取token。 就一直重新checkToken。

**Comment by cqnature** [comment]
问题已修复。dev-0.2.0版提交
