### ISSUE TITLE
战斗中带胎4踢腿龙进去，踢腿龙释放AOE技能的时候，会遇到怪有护盾的情况。这个情况也会出现在英雄释放普攻，但是踢腿龙没有攻击的情况下  P0

### ISSUE THREAD

**Issue by Zimering** [aoxu/std2#753]
![](http://ww1.sinaimg.cn/mw690/006wqYXMgy1fiw0turhdzj31120kudh7.jpg)
就是弱鸡龙身上的这个护盾，踢腿龙有时候打到小怪身上也会出现，打到BOSS身上也会出现。
有时候踢腿龙没攻击，英雄普通攻击也会出现这个BUG

**Comment by cqusyc** [comment]
这个护盾是通用效果，当英雄侧子弹打到不可被伤害的小怪时，会触发该效果
