### ISSUE TITLE
宠物寄养功能的标题栏应该显示的是宠物寄养，但是现在显示是已寄养

### ISSUE THREAD

**Issue by Zimering** [aoxu/std2#857]
![](http://ww1.sinaimg.cn/mw690/006wqYXMgy1fk0adkx5wcj30j90b4abc.jpg)

**Comment by cqnature** [comment]
FOSTER CREW ({0}/{1}),已寄养 ,CAMPED CREW(S) ({0}/{1}),,

@Zimering  改下文案吧
