### ISSUE TITLE
nero 删除游戏后新安装，收到我们游戏的 Facebook 邀请后，打开游戏，却提示用 旧的Facebook 账号登录～

### ISSUE THREAD

**Issue by aoxu** [aoxu/std2#881]
nero的状态是删除了游戏，又重新安装了线上版本，没有登录 Facebook ，我从游戏里邀请了她的Facebook账号（叫nero weed），她那个Facebook账号从来没绑定过游戏～
她从Facebook App（此时登录的账号是nero weed）收到邀请后，接受，跳转到我们游戏，打开游戏登录Facebook，游戏内打开一个Facebook的网页，提示她“你之前用这个Facebook账号（叫汤雨琪）登录过Star Raiders，是否继续”，这一步点取消，就会退出登录流程，回到登录前的界面，无法切换，如果点继续，就会登录到“汤雨琪“的账号，游戏里拉到的是”汤雨琪“绑过的游戏数据。。。导致最终邀请好友的流程无法成功继续～
这里的问题奇怪的是，她的Facebook App里登录的是nero weed，但是登录时却提示的是汤雨琪，为什么？

**Comment by Kinderzhang** [comment]
APP的记录跟网页的记录不是共用的 你应该用网页退出facebook~

**Comment by Kinderzhang** [comment]
APP的你可以理解为跟QQ的一样 只用来登录验证的。 网页版那个是你手动登录过。所以有记录的
